### ISSUE TITLE
Add support for SQL projections into nested types

### ISSUE THREAD

**Issue by andygrove** [andygrove/datafusion#101]
Currently it is not possible to select attributes within structs from SQL. We need to add the ability to do this e.g. `SELECT customer.address.state FROM ...`

**Comment by dthg** [comment]
Hey @andygrove, I'd be interested in contributing to the project. Would this be a good starting issue? Quite new to Rust but resonably familiar with Spark.

**Comment by dthg** [comment]
Thanks for the reply @andygrove! Started working on this, gotten to the point where I can reproduce the error

**Comment by dthg** [comment]
Hi @andygrove sorry about the lack of communication, still interested in this issue.

So far I have done two things to nail down the issue.
- Firstly I've added a failing test for the something like the `ST_Point(lat, lng).lat` case.
```rust
    #[test]
    fn parse_pojection_function() {
        let sql = String::from("SELECT bar(a, b).c FROM foo");
        let _ast = parse_sql(&sql);
        //TODO: add assertions
    }
```
- Secondly the schema of the df in `csv_sql.rs` to contain a struct field e.g.
```rust
    let schema = Schema::new(vec![
        Field::new("city", DataType::Utf8, false),
        Field::new(
            "bar",
            DataType::Struct(vec![
                Field::new("a", DataType::Utf8, false),
                Field::new("b", DataType::Utf8, false),
            ]),
            false,
        ),
        Field::new("lat", DataType::Float64, false),
        Field::new("lng", DataType::Float64, false),
    ]);
```
Then modified the query to look like ``SELECT bar.b...`

Both of these test cases fail, however the first case fails with a parsing error, and the second in `sql_to_rex`  with an unsupported node type.

I quickly hacked together something for the second case, just adding a section for `ASTNode::SQLCompoundFields`.  
For the first case I wasn't quite sure how  `function().field` should be represented in the AST, what would you suggest?
