### ISSUE TITLE
Design struct for distributed jobs

### ISSUE THREAD

**Issue by andygrove** [andygrove/datafusion#12]
First use case should be sending a job to read a csv file and partition it into multiple csv files

**Comment by AnirudhVyas** [comment]
Do you have any architectural design for distributed processing? E.g is your distributed system going to be Master Worker, or peer to peer - and maybe reasoning for such a choice. I am very excited to see this happen - I am a Rust Newbie but I build data ingestion and processing systems in Go, Scala and Spark at work - And I feel Rust could really shine here.
