### ISSUE TITLE
data locality in k8s

### ISSUE THREAD

**Issue by geoHeil** [andygrove/datafusion#141]
How do you handle data locality in Kubernetes?

**Comment by andygrove** [comment]
How would you like it to work?

I'm in the process of planning the distributed parts of DataFusion and have been looking at implementing HDFS support but I'm concerned how long that will take and I'm not crazy about the overhead of HDFS so if there is a good way I have DataFusion rely on local files for each node/container that will make it much easier to get to a distributed release.

So I'm interested to hear about your use case.

**Comment by geoHeil** [comment]
I currently can't contribute a usecase. Currently, I am using spark but recently have developed some interest for Rust. Your project as well as differential data flow look interesting.

As far as I know running hadoop in Kubernetes is still a somewhat open problem. At the Dataworkssummit in Berlin some Hortonworks people told me they plan to launch a gigantic YARN container on some of the k8s nodes which colocates then HDFS + your analytics framework of choice.
