### ISSUE TITLE
Add HDFS support

### ISSUE THREAD

**Issue by andygrove** [andygrove/datafusion#144]
Many people require HDFS support before they can really try out DataFusion.

The best path for implementing this seems to be to leverage the C++ HDFS support in Apache Arrow.

To support Parquet on HDFS we will need to implement Rust traits such as `Read` and `Seek` on top of the HDFS client.

**Comment by hntd187** [comment]
So I researched this a bit and it's kind of a lot more of a pain than I had thought. Rust's interop with C++ is kind of in an odd state, but it's possible. I think though the code involved in something like that would be pretty dirty. There is a C lib for Arrow, but it's a wrapper around the C++ library. My other looks at rust based HDFS libraries didn't yield anything actively maintained or stand out. Perhaps the right way is to wrap some aspects of Hadoop's libhdfs, which is C or to write ground up HDFS support. What is your opinion on this?
