### ISSUE TITLE
DataFrame compile-time schema

### ISSUE THREAD

**Issue by crepererum** [andygrove/datafusion#94]
## Abstract
Right now, you every time you want to access a column of a DF, you need an unwrap (`df1.col("lat").unwrap();`). That's because at an arbitrary position of the code, you cannot make safe assumptions about which columns are present in a DF. That's a problem that is kinda inherited from pandas. At the same time, many data processing functions could easily specify which columns they need and which columns they produce.

## Solution
I propose some kind of `TypedDataFrame`/`SafeDataFrame`/`CheckedDataFrame` (name could differ) that specifies which columns are present and a some kind of try-into mechanism from the normal, unchecked DF into the checked DF (see [`TryInto`](https://doc.rust-lang.org/std/convert/trait.TryInto.html)). Also, there should be a simple macro to generate new schemas.

## Example Usage
```rust

// compile time version of an Arrow schema
schema!(
    DFHealth,
    [
        (n_people, UInt32, False),
        (p_sick, Float64, False),
        (city, Utf8, False),
    ]
);

fn sum_people(df: DFHealth) -> u32 {
   // no unwrap required, we already know that df has all required columns
   df.col.n_people().iter().sum()
}

fn load_df() -> DataFrame {
    ...
}

fn main() {
    let df: DFHealth = load_df(...).try_into()?;
    let people = sum_people(df);

    // since schema is known at compile time, we can easily get the arrow schema from it
    // (compile time information => runtime information)
    let schema = DFHealth.schema();
}
```

## Prior Art
- [Table Enforcer](https://github.com/xguse/table_enforcer) (for Pandas, covers some more features)
- [Arrow Schema](https://github.com/apache/arrow/blob/master/rust/src/datatypes.rs) (already used, but only as runtime information)

**Comment by andygrove** [comment]
Thanks for the suggestion. I like the idea and will give this some thought. The focus so far has very much been on dynamic behavior but I like the idea of type-safety with predefined types like this.
